# Generated by Django 4.2.6 on 2023-11-16 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_rename_images_employee_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
